// Code generated by "stringer -type=AQIStandard"; DO NOT EDIT.

package goaqi

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[AQISTANDARD_UNSPECIFIED-0]
	_ = x[AQISTANDARD_US-1]
	_ = x[AQISTANDARD_CN-2]
}

const _AQIStandard_name = "AQISTANDARD_UNSPECIFIEDAQISTANDARD_USAQISTANDARD_CN"

var _AQIStandard_index = [...]uint8{0, 23, 37, 51}

func (i AQIStandard) String() string {
	if i < 0 || i >= AQIStandard(len(_AQIStandard_index)-1) {
		return "AQIStandard(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _AQIStandard_name[_AQIStandard_index[i]:_AQIStandard_index[i+1]]
}
