// Code generated by "stringer -type=Pollutant"; DO NOT EDIT.

package goaqi

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[UNKNOWN-0]
	_ = x[AQI-1]
	_ = x[O3_1H-10]
	_ = x[O3_8H-11]
	_ = x[PM2_5_1H-20]
	_ = x[PM2_5_24H-21]
	_ = x[PM10_1H-30]
	_ = x[PM10_24H-31]
	_ = x[SO2_1H-40]
	_ = x[SO2_24H-41]
	_ = x[NO2_1H-50]
	_ = x[NO2_24H-51]
	_ = x[CO_1H-60]
	_ = x[CO_8H-61]
	_ = x[CO_24H-62]
}

const (
	_Pollutant_name_0 = "UNKNOWNAQI"
	_Pollutant_name_1 = "O3_1HO3_8H"
	_Pollutant_name_2 = "PM2_5_1HPM2_5_24H"
	_Pollutant_name_3 = "PM10_1HPM10_24H"
	_Pollutant_name_4 = "SO2_1HSO2_24H"
	_Pollutant_name_5 = "NO2_1HNO2_24H"
	_Pollutant_name_6 = "CO_1HCO_8HCO_24H"
)

var (
	_Pollutant_index_0 = [...]uint8{0, 7, 10}
	_Pollutant_index_1 = [...]uint8{0, 5, 10}
	_Pollutant_index_2 = [...]uint8{0, 8, 17}
	_Pollutant_index_3 = [...]uint8{0, 7, 15}
	_Pollutant_index_4 = [...]uint8{0, 6, 13}
	_Pollutant_index_5 = [...]uint8{0, 6, 13}
	_Pollutant_index_6 = [...]uint8{0, 5, 10, 16}
)

func (i Pollutant) String() string {
	switch {
	case 0 <= i && i <= 1:
		return _Pollutant_name_0[_Pollutant_index_0[i]:_Pollutant_index_0[i+1]]
	case 10 <= i && i <= 11:
		i -= 10
		return _Pollutant_name_1[_Pollutant_index_1[i]:_Pollutant_index_1[i+1]]
	case 20 <= i && i <= 21:
		i -= 20
		return _Pollutant_name_2[_Pollutant_index_2[i]:_Pollutant_index_2[i+1]]
	case 30 <= i && i <= 31:
		i -= 30
		return _Pollutant_name_3[_Pollutant_index_3[i]:_Pollutant_index_3[i+1]]
	case 40 <= i && i <= 41:
		i -= 40
		return _Pollutant_name_4[_Pollutant_index_4[i]:_Pollutant_index_4[i+1]]
	case 50 <= i && i <= 51:
		i -= 50
		return _Pollutant_name_5[_Pollutant_index_5[i]:_Pollutant_index_5[i+1]]
	case 60 <= i && i <= 62:
		i -= 60
		return _Pollutant_name_6[_Pollutant_index_6[i]:_Pollutant_index_6[i+1]]
	default:
		return "Pollutant(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
